'''
# this is the code for integrating LangChain + OpenAI API to get better performance
import os
import pandas as pd
from langchain_experimental.agents import create_pandas_dataframe_agent
from langchain_openai import ChatOpenAI
from eduscope.data import load_dataset

# Load your dataset
df = load_dataset()

# Initialize the OpenAI model (you’ll enter your API key soon)
os.environ["OPENAI_API_KEY"] = "YOUR OWN API KEY"
# Create the agent with LangChain
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)
agent = create_pandas_dataframe_agent(llm, df, verbose=True)

def ask_ai(query: str):
    """
    Passes a natural language question to the AI agent 
    and returns the response generated by the model.
    """
    try:
        response = agent.invoke(query)
        return response["output"]
    except Exception as e:
        return f"Error: {str(e)}"

if __name__ == "__main__":
    print("🔹 EduScopeAI – LangChain + OpenAI Mode")
    while True:
        query = input("\nAsk your question (or type 'exit' to stop): ")
        if query.lower() == "exit":
            print("Session ended.")
            break
        result = ask_ai(query)
        print("\n🧠 AI Response:\n", result)
'''

# this is the code for integrating the LangChain + Ollama for offline working case
import pandas as pd
from langchain_ollama import ChatOllama
from langchain_experimental.agents.agent_toolkits.pandas.base import create_pandas_dataframe_agent
from eduscope.data import load_dataset

# Load dataset
df = load_dataset()

# Initialize Ollama model (local model)
llm = ChatOllama(model="llama3", temperature=0)

# Create LangChain dataframe agent
agent = create_pandas_dataframe_agent(
    llm,
    df,
    verbose=True,
    allow_dangerous_code=True
)

def ask_ai(query: str):
    """Ask natural language questions to the AI agent."""
    try:
        response = agent.invoke(query)
        return response["output"]
    except Exception as e:
        return f"Error: {str(e)}"

if __name__ == "__main__":
    print("🔹 EduScopeAI – LangChain + Ollama Mode")
    while True:
        query = input("\nAsk your question (or type 'exit' to stop): ")
        if query.lower() == "exit":
            print("Session ended.")
            break
        result = ask_ai(query)
        print("\n🧠 AI Response:\n", result)
